apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eidas-node.fullname" . }}
  labels:
    {{- include "eidas-node.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "eidas-node.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "eidas-node.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "eidas-node.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if and .Values.configurationViaDownload.enabled .Values.configurationViaDownload.downloadUrl }}
      volumes:
        - name: keystore-volume
          emptyDir: {}
        - name: config-volume
          emptyDir: {}
        {{- if .Values.volumes }}
          {{- toYaml .Values.volumes | nindent 8 }}
        {{- end }}
      initContainers:
        - name: download-config
          image: alpine:3.14.0
          imagePullPolicy: Always
          command:
          - "/bin/ash"
          - "-c"
          - "wget -O /data/config.zip {{ .Values.configurationViaDownload.downloadUrl }} && unzip -o /data/config.zip -d /data && rm /data/config.zip"
          volumeMounts:
          - name: keystore-volume
            mountPath: "/data/keystore"
          - name: config-volume
            mountPath: "/data/config"
      {{- else }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      {{- end }}
      containers:
        - name: eidas-node
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          {{- if .Values.envs }}
          env:
            {{- toYaml .Values.envs | nindent 10 }}
          {{- end }}
          {{- if .Values.probes }}
            {{- toYaml .Values.probes | nindent 10 }}
          {{- end }}
          {{- if and .Values.configurationViaDownload.enabled .Values.configurationViaDownload.downloadUrl }}
          volumeMounts:
            - name: keystore-volume
              mountPath: /config/keystore
            - name: config-volume
              mountPath: /config/eidas
            {{- if .Values.volumeMounts }}
              {{- toYaml .Values.volumeMounts | nindent 12 }}
            {{- end }}
          {{- else }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
